services:
  django: &django
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DJANGO_SETTINGS_MODULE
      - DJANGO_SECRET_KEY
      - DATABASE_URL
      - REDIS_URL
      - CELERY_FLOWER_USER
      - CELERY_FLOWER_PASSWORD

  postgres:
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  # celeryworker:
  #   environment:
  # - REDIS_URL
  # - CELERY_BROKER_URL

  # celerybeat:
  #   environment:
  #     - REDIS_URL
  # - CELERY_BROKER_URL
