# Local dev overrides
services:
  django: &django
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres

  postgres:
    env_file:
      - ./.envs/.local/.postgres

  docs:
    env_file:
      - ./.envs/.local/.django

  celeryworker:
    <<: *django

  celerybeat:
    <<: *django

  flower:
    <<: *django
