# Canonical configuration for the services

# The order of precedence (highest to lowest) is as follows:

# Set using docker compose run -e in the CLI
# Substituted from your shell
# Set using the environment attribute in the Compose file
# Use of the --env-file argument in the CLI
# Use of the env_file attribute in the Compose file
# Set using an .env file placed at base of your project directory
# Set in a container image in the ENV directive. Having any ARG or ENV setting in a Dockerfile evaluates only if there is no Docker Compose entry for environment, env_file or run --env.

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: price_navigator_local_django
    container_name: price_navigator_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: price_navigator_production_postgres
    container_name: price_navigator_local_postgres
    volumes:
      - price_navigator_local_postgres_data:/var/lib/postgresql/data
      - price_navigator_local_postgres_data_backups:/backups

  docs:
    image: price_navigator_local_docs
    container_name: price_navigator_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./price_navigator:/app/price_navigator:z
    ports:
      - '9000:9000'
    command: /start-docs

  redis:
    image: redis:6
    container_name: price_navigator_local_redis

  celeryworker:
    <<: *django
    image: price_navigator_local_celeryworker
    container_name: price_navigator_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: price_navigator_local_celerybeat
    container_name: price_navigator_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: price_navigator_local_flower
    container_name: price_navigator_local_flower
    ports:
      - '5555:5555'
    command: /start-flower

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: price_navigator_local_node
    container_name: price_navigator_local_node
    depends_on:
      - django
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev
    ports:
      - '3000:3000'

volumes:
  price_navigator_local_postgres_data:
    name: 'price-navigator-warehouse'
    labels:
      com.example.description: 'Database volume'
      com.example.department: 'IT/Ops'
      com.example.label-with-empty-value: ''
  price_navigator_local_postgres_data_backups:
    name: 'price-navigator-backups-dir-for-warehouse'
